#!/bin/sh
[ -z $1 ] && echo -e "Usage: $0 x.y.z" && exit 1;
VERSION=$1

cat android/app/build.gradle  | sed "/versionName/ s/\".*\"/\"$VERSION\"/" > /tmp/build.gradle
mv /tmp/build.gradle android/app/

cat pebble/package.json  | sed "/version/ s/: \".*\"/: \"$VERSION\"/" > /tmp/package.json
mv /tmp/package.json pebble/

for SF in `find android/app/src/main/res -name strings.xml`; do
	echo $SF
	cat $SF | sed "/app_version/ s/[0-9].*</$VERSION</" > /tmp/strings.xml
	mv /tmp/strings.xml $SF
done

cd pebble
~/pebble-dev/pebble-sdk-4.5-linux64/bin/pebble build || exit 2
cd ..

cd android
gradle clean
gradle assembleRelease || exit 3
mv app/build/outputs/apk/sologyr-release.apk app/
cd ..

git commit -a -m "tag version $VERSION" -e
git tag "$VERSION"

